Suppress UBSAN alignment warning in CI kernel config
While running the kernel tests in the CI, there are many instances of the
error: "UBSAN misaligned-access in <source>". This likely due to the fact
that when UBSAN was introduced, the authors didn't fix the warnings for the
User Mode Linux.

As a temporary workaround, until the issues reported by UBSAN are fixed,
disable CONFIG_UBSAN_ALIGNMENT to suppress the warnings.

Signed-off-by: Roberto Sassu <roberto.sassu@huawei.com>